### ISSUE TITLE
MongoSessionIdManager uses deprecated ensureIndex

### ISSUE THREAD

**Issue by ssasa** [eclipse/jetty.project#641]
Hi,
MongoSessionIdManager uses ensureIndex which is deprecated which results with an error such as this:

```
java.lang.NoSuchMethodError: com.mongodb.DBCollection.ensureIndex(Lcom/mongodb/DBObject;Lcom/mongodb/DBObject;)V
        at org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager.<init>(MongoSessionIdManager.java:186)
        at org.eclipse.jetty.nosql.mongodb.MongoSessionIdManager.<init>(MongoSessionIdManager.java:175)
```

According to link below, createIndex() should be used inste of ensureIndex():

https://stackoverflow.com/questions/25968592/difference-between-createindex-and-ensureindex-in-java-using-mongodb/26386601

Thanks!
Sasa

**Comment by janbartel** [comment]
#611 also addresses version compatibility issues.  However, it looks like version 2.6.1 that jetty is currently using, and versions 3.2.x  both support the use of createIndex, so I'm happy to just make this one change, whilst leaving open issue #611 to address an upgrade to the version of mongodb.

**Comment by janbartel** [comment]
I've checked in  a change to use createIndex, which seems to work with mongo 2.6.1 up thru mongo 2.12.x to 3.2.2.
