### ISSUE TITLE
Jetty 10.0.13-java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletMapping

### ISSUE THREAD

**Issue by sushikarwasra** [eclipse/jetty.project#9290]
**Jetty version**
10.0.13
**Java version**
JDK17
**Question**
After upgrade to 10.0.13 i am seeing below in server logs, please suggest how this can be fixed.

2023-02-02 13:39:02,487  WARN [qtp1527430292-130] org.eclipse.jetty.io.ManagedSelector - Could not accept java.nio.channels.SocketChannel[closed]: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletMapping

**Comment by janbartel** [comment]
@sushikarwasra you need to provide some more information about how you're running jetty, what modules etc you have enabled, what custom modules, configuration etc you might have. More than likely you have duplicate jars on the classpath, some of which are old versions.

**Comment by sushikarwasra** [comment]
@janbartel i am not using any custom modules, i have below jar in my server lib folder, any suggestion if i am missing any jar or any duplicate jar that may cause the above error.
-r--r--r-- 1   122445 Feb  7 04:42 asm-9.4.jar
-r--r--r-- 1    72781 Feb  7 04:42 asm-commons-9.4.jar
-r--r--r-- 1    52665 Feb  7 04:42 asm-tree-9.4.jar
-r--r--r-- 1   436303 Feb  7 04:41 avro-1.7.7.jar
-r--r--r-- 1   214381 Feb  7 04:41 checker-qual-3.5.0.jar
-r--r--r-- 1   506096 Feb  7 04:41 classgraph-4.8.87.jar
-r--r--r-- 1    44982 Feb  7 04:41 common.core-0.0.20.jar
-r--r--r-- 1   425643 Feb  7 04:41 commons-compress-1.11.jar
-r--r--r-- 1   100311 Feb  7 04:41 compiler-0.9.4.jar
-r--r--r-- 1   118004 Feb  7 04:41 config_manager-1.1-SNAPSHOT.jar
-r--r--r-- 1    13879 Feb  7 04:41 error_prone_annotations-2.3.4.jar
-r--r--r-- 1     4617 Feb  7 04:41 failureaccess-1.0.1.jar
-r--r--r-- 1   229650 Feb  7 04:41 gson-2.6.2.jar
-r--r--r-- 1  2858426 Feb  7 04:41 guava-30.0-jre.jar
-r--r--r-- 1    26323 Feb  7 04:42 http2-client-10.0.13.jar
-r--r--r-- 1   232215 Feb  7 04:42 http2-common-10.0.13.jar
-r--r--r-- 1    53241 Feb  7 04:42 http2-hpack-10.0.13.jar
-r--r--r-- 1    71613 Feb  7 04:42 http2-server-10.0.13.jar
-r--r--r-- 1     8781 Feb  7 04:41 j2objc-annotations-1.3.jar
-r--r--r-- 1   232248 Feb  7 04:41 jackson-core-asl-1.9.13.jar
-r--r--r-- 1   780664 Feb  7 04:41 jackson-mapper-asl-1.9.13.jar
-r--r--r-- 1    25058 Feb  7 04:41 jakarta.annotation-api-1.3.5.jar
-r--r--r-- 1    15392 Feb  7 04:42 jakarta.transaction-api-1.3.3.jar
-r--r--r-- 1    56674 Feb  7 04:40 javax.activation-api-1.2.0.jar
-r--r--r-- 1    26586 Feb  7 04:42 javax.annotation-api-1.3.2.jar
-r--r--r-- 1    40621 Feb  7 04:42 javax.security.auth.message-1.0.0.v201108011116.jar
-r--r--r-- 1    51862 Feb  7 04:42 javax.security.auth.message-api-1.1.jar
-r--r--r-- 1    95806 Feb  7 04:41 javax.servlet-api-3.1.0.jar
-r--r--r-- 1   128076 Feb  7 04:40 jaxb-api-2.3.1.jar
-r--r--r-- 1    16555 Feb  7 04:41 jcl-over-slf4j-1.7.36.jar
-r--r--r-- 1    16949 Feb  7 04:42 jetty-alpn-client-10.0.13.jar
-r--r--r-- 1    95059 Feb  7 04:42 jetty-annotations-10.0.13.jar
-r--r--r-- 1   393209 Feb  7 04:42 jetty-client-10.0.13.jar
-r--r--r-- 1    66737 Feb  7 04:41 jetty-deploy-10.0.13.jar
-r--r--r-- 1   249269 Feb  7 04:41 jetty-http-10.0.13.jar
-r--r--r-- 1   216493 Feb  7 04:41 jetty-io-10.0.13.jar
-r--r--r-- 1    43140 Feb  7 04:42 jetty-jaspi-10.0.13.jar
-r--r--r-- 1    41500 Feb  7 04:42 jetty-jmx-10.0.13.jar
-r--r--r-- 1    48018 Feb  7 04:42 jetty-jndi-10.0.13.jar
-r--r--r-- 1    69096 Feb  7 04:42 jetty-plus-10.0.13.jar
-r--r--r-- 1    51191 Feb  7 04:42 jetty-quickstart-10.0.13.jar
-r--r--r-- 1    50080 Feb  7 04:42 jetty-rewrite-10.0.13.jar
-r--r--r-- 1   121209 Feb  7 04:41 jetty-security-10.0.13.jar
-r--r--r-- 1   795839 Feb  7 04:41 jetty-server-10.0.13.jar
-r--r--r-- 1   165857 Feb  7 04:41 jetty-servlet-10.0.13.jar
-r--r--r-- 1   273076 Feb  7 04:41 jetty-servlet-api-4.0.6.jar
-r--r--r-- 1   100983 Feb  7 04:42 jetty-servlets-10.0.13.jar
-r--r--r-- 1   174067 Feb  7 04:42 jetty-start-10.0.13.jar
-r--r--r-- 1   568193 Feb  7 04:41 jetty-util-10.0.13.jar
-r--r--r-- 1   158900 Feb  7 04:41 jetty-webapp-10.0.13.jar
-r--r--r-- 1    72310 Feb  7 04:41 jetty-xml-10.0.13.jar
-r--r--r-- 1     6282 Feb  7 04:41 jmetrics.annotation-0.0.17.jar
-r--r--r-- 1    16591 Feb  7 04:41 jmetrics.jmx-0.0.17.jar
-r--r--r-- 1    19936 Feb  7 04:41 jsr305-3.0.2.jar
-r--r--r-- 1     2199 Feb  7 04:41 listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
-r--r--r-- 1    23715 Feb  7 04:41 log4j-over-slf4j-1.7.36.jar
-r--r--r-- 1   231851 Feb  7 04:41 logback-classic-1.2.11.jar
-r--r--r-- 1   448764 Feb  7 04:41 logback-core-1.2.11.jar
-r--r--r-- 1    17109 Feb  7 04:41 logfast.core-1.0.6.jar
-r--r--r-- 1     6701 Feb  7 04:41 logger_data-1.1-SNAPSHOT.jar
-r--r--r-- 1    29555 Feb  7 04:41 paranamer-2.3.jar
-r--r--r-- 1    41125 Feb  7 04:41 slf4j-api-1.7.36.jar
-r--r--r-- 1  1251514 Feb  7 04:41 snappy-java-1.0.5.jar
-r--r--r-- 1   195345 Feb  7 04:42 websocket-core-common-10.0.13.jar
-r--r--r-- 1    64714 Feb  7 04:42 websocket-core-server-10.0.13.jar
-r--r--r-- 1    17640 Feb  7 04:42 websocket-servlet-10.0.13.jar

**Comment by joakime** [comment]
The existence of jar files in the lib directory means very little. (the jar files present in the server classloader are used based on what modules you have selected, and precise names in the lib directory specified in those modules)

Do this and report the output ...

``` shell
$ cd /path/to/my-jetty-base
$ java -jar /path/to/jetty-home/start.jar --list-config
```

Note: it's important that the 2 directories (`${jetty.base}` and `${jetty.home}`) are separate locations that are not nested within each other.

**Comment by joakime** [comment]
This is important.
Don't change / edit / remove / add any content in the `${jetty.home}` directory.
It's to be considered read-only once you unpack it.
Create a `${jetty.base}` directory and manage your instance configuration there, including extra libs and whatnot.

The fact that you are putting custom libs along side the standard libs screams of misuse of jetty-home and the whole jetty-home vs jetty-base split.

I can already see lib conflicts in that listing you provided ...

_Delete this:_
```
-r--r--r-- 1 95806 Feb 7 04:41 javax.servlet-api-3.1.0.jar
```

Jetty 10 is based on Jakarta Servlet 4 (namespace `javax.servlet`), get rid of that jar above, it doesn't have HttpServletMapping in it.


```
-r--r--r-- 1 273076 Feb 7 04:41 jetty-servlet-api-4.0.6.jar
```

This is the jar handling the Servlet 4 API, and is the one holding the class `javax.servlet.http.HttpServletMapping`.

---

Jetty logging is based on slf4j 2.x

Get rid of the following slf4j 1.x series jars in your `lib/` tree.

_Delete these and use the Jetty module system to get the correct jars:_
```
-r--r--r-- 1 41125 Feb 7 04:41 slf4j-api-1.7.36.jar
-r--r--r-- 1 16555 Feb 7 04:41 jcl-over-slf4j-1.7.36.jar
-r--r--r-- 1 23715 Feb 7 04:41 log4j-over-slf4j-1.7.36.jar
-r--r--r-- 1 231851 Feb 7 04:41 logback-classic-1.2.11.jar
-r--r--r-- 1 448764 Feb 7 04:41 logback-core-1.2.11.jar
```

Use the Jetty module system to select the appropriate logger bridges and implementations, don't manually put stuff in the `${jetty.home}/lib/` directory. See `start.jar --list-modules` for the list of modules available.

----

You have obvious conflicts in jars as well, these 2 should not exist in the `lib/` directory at all.

_Delete these and use the Jetty module system and get the correct jars:_
```
-r--r--r-- 1 25058 Feb 7 04:41 jakarta.annotation-api-1.3.5.jar
-r--r--r-- 1 26586 Feb 7 04:42 javax.annotation-api-1.3.2.jar
```

Nor should the asm jars, those are loaded by the module system from the `lib/annotations/` tree. (depending on which modules you have enabled).

_Delete these and use the Jetty module system to get the correct jars:_
```
-r--r--r-- 1 122445 Feb 7 04:42 asm-9.4.jar
-r--r--r-- 1 72781 Feb 7 04:42 asm-commons-9.4.jar
-r--r--r-- 1 52665 Feb 7 04:42 asm-tree-9.4.jar
```

The http2 jars are incomplete.  These are in the `lib/http2/` tree and have associated alpn jars that you are missing.

_Delete these and use the Jetty module system:_
```
-r--r--r-- 1 26323 Feb 7 04:42 http2-client-10.0.13.jar
-r--r--r-- 1 232215 Feb 7 04:42 http2-common-10.0.13.jar
-r--r--r-- 1 53241 Feb 7 04:42 http2-hpack-10.0.13.jar
-r--r--r-- 1 71613 Feb 7 04:42 http2-server-10.0.13.jar
-r--r--r-- 1 16949 Feb 7 04:42 jetty-alpn-client-10.0.13.jar
```

**Comment by sushikarwasra** [comment]
@joakime if i remove javax.servlet-api-3.1.0.jar and keep only jetty-servlet-api-4.0.6.jar then i get below error
2023-02-09 07:13:50,979  WARN [main] org.eclipse.jetty.xml.XmlConfiguration - Unable to execute XmlConfiguration
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3429)
	at java.base/java.lang.Class.getConstructors(Class.java:2110)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.construct(XmlConfiguration.java:995)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:400)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:319)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1818)

**Comment by janbartel** [comment]
@sushikarwasra as I've said in one of your other questions, if I were you, I would start with a fresh distribution of jetty-10, enable the modules you think you need, copy in your webapp and context xml file (if you have one). Then see what is working/not working. Also make sure you've read the jetty-10 operations guide for info on the modules you might need to enable: https://www.eclipse.org/jetty/documentation/jetty-10/operations-guide/index.html

**Comment by sushikarwasra** [comment]
yes @janbartel i followed the steps and started with fresh distribution of jetty-10 only, problem is if i don't keep the javax.servlet-api-3.1.0.jar  then i get java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse

**Comment by janbartel** [comment]
@sushikarwasra there is something wrong with your environment then because you should never have javax.servlet-api-3.1.0.jar in jetty-10.  You are going to have to provide more information about  your setup, for example you could paste the results of `java -jar $jetty.home/start.jar --list-config`.

**Comment by sushikarwasra** [comment]
@janbartel i have to bundle the jetty home(with all the files in etc,mod and jars) with the project using the maven build so that once the build is complete and it is deployed on server we have jetty home with all the xml, mod and jars  etc. similar to jetty home in jetty-home-10.0.13.zip that i download from eclipse website with below structure. Some of the jar e.g. javax.servlet was getting added into lib from parent pom that i have now removed and i wanted to keep only the jar that jetty home comes with so that jetty can be started.
jetty_home
                   -----bin
                   -----etc
                   -----lib
                   ------module

**Comment by janbartel** [comment]
@sushikarwasra in addition to `jetty-home` you deploy your webapp to a `jetty-base`, right?  And is everything now working? I can't tell from your last post.

**Comment by sushikarwasra** [comment]
Yes @janbartel i deploy in webapps in jetty-base, but the problem is with jetty-home packaging using maven, i am not able to package the jetty-home with only dependencies that are available in jetty-home-10.0.13.zip lib folder, once i build the jetty by adding dependency in pom.xml many other dependent dependencies  also get added into lib folder e.g. infinispan-common add wildfly-common and wildfly-elytron.

**Comment by janbartel** [comment]
@sushikarwasra `jetty-home` isn't intended to be the kind of maven artifact that you should use as a dependency like that. Your pom should probably use the `maven-dependency-plugin` to unpack `jetty-home` to target somewhere, copy over your webapp then tar/zip that whole thing up as the product of the build.

**Comment by janbartel** [comment]
Advice given, and no further input so closing issue.
