### ISSUE TITLE
HTTP/2 stopped working with Jetty 12.0.2 (just hangs [no reply] using Chrome)

### ISSUE THREAD

**Issue by minduch** [eclipse/jetty.project#10729]
**Jetty version(s)**
Jetty 12.0.2

**Jetty Environment**
Embedded Jetty 12.0.2 in IIZI (latest version download at https://support.iizi.co)

**Java version/vendor** `(use: java -version)`
Java (Temurin x86_64) 17.0.8.1 or 21

**OS type/version**
Linux Feodora 38, x86_64

**Description**
The HTTP/2 implementation does not send any responses using Jetty 12.0.2. Previous Jetty version 12.0.1 or earlier (beta/alpha) worked fine.

**How to reproduce?**
Using the IIZI server, but it's complicated. I'd rather attempt to locate the problem, but I don't know where to look. I can turn on Jetty traces, but what should I be looking for, or do you want a debug output?

We have a public server at "https://mt.iizi.co" running IIZI and Jetty 12.0.2. Currently, to make it work, we have turned off HTTP/2. When HTTP/1 + 2 is used, "curl" commands works fine when using HTTP/1.1. Requesting the home page "https://mt.iizi.co" from Chrome 117/118 just hangs or no-replies, and so does every/any other requests.

**Comment by sbordet** [comment]
A DEBUG output attached to this issue would be a good start.

Chrome 118 works fine with our own website, so it must be some corner case.

**Comment by minduch** [comment]
This is what happens,

```
(java.lang.NoSuchMethodError: 'int org.eclipse.jetty.http2.hpack.HpackDecoder.getMaxHeaderListSize()'
                at org.eclipse.jetty.http2.parser.Parser.init(Parser.java:77)
                at org.eclipse.jetty.http2.parser.ServerParser.init(ServerParser.java:43)
                at org.eclipse.jetty.http2.server.AbstractHTTP2ServerConnectionFactory.newConnection(AbstractHTTP2ServerConnectionFactory.java:333)
                at org.eclipse.jetty.server.NegotiatingServerConnection.onFillable(NegotiatingServerConnection.java:124)
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
                at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:554)
                at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:373)
                at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
                at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
                at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
                at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```
causing all sorts of interesting things to happen. See logs `server-http1.log` and `server-http2.log` for server log with Jetty debug logging enabled for HTTP/1.1 only and HTTP/2 also, respectively.

[server-http1.log](https://github.com/jetty/jetty.project/files/12887544/server-http1.log)
[server-http2.log](https://github.com/jetty/jetty.project/files/12887545/server-http2.log)

**Comment by minduch** [comment]
Our HTTP/1.1 and HTTP/2 connectors are extending the default `ServerConnector` class to hold additional information using the interface `IServerConnector` (not relevant here).

The code looks like:

```java
package com.iizix.jetty;

import org.eclipse.jetty.server.ConnectionFactory;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;

import com.iizix.comm.IServerConnector;
import com.iizix.comm.PortConfig;

/**
 * The web server connection processing a request is associated with a port configuration
 * for HTTP/1.1 and HTTP/2 (clear text and TLS).
 * 
 * @author Christopher Mindus
 */
class WSServerConnector extends ServerConnector implements IServerConnector
{
  /**
   * The port configuration.
   */
  private final PortConfig portConfig;
  
  ///
  
  /**
   * Constructor for HTTP/1.1 and HTTP/2 (clear text and TLS).
   * 
   * @param server     The server.
   * @param factories  The connection factories.
   */
  WSServerConnector(PortConfig portConfig,Server server,ConnectionFactory... factories)
    {
    super(server,factories);
    this.portConfig=portConfig;
    }
  
  /**
   * Gets the port configuration for this server connection.
   * 
   * @return  The port configuration.
   */
  @Override
  public PortConfig getPortConfig()
    {
    return portConfig;
    }
}
```

in case you need to know...

**Comment by sbordet** [comment]
You likely have a mismatch of the jars you are using for your server.

Likely you are using `jetty-http2-common:12.0.2`, but `jetty-http2-hpack:12.0.1` or an older version.

Please get all the Jetty jars at the same version.

**Comment by minduch** [comment]
You're right: we forgot to delete the Jetty 12.0.1 jars in only the http2 package, so we had both versions. I guess the classpath takes v12.0.1 before v12.0.2 as we didn't specify an order but rather `http/*` (yes a little dangerous, I agree).

Thanks a lot. I will start a new build and get back to this issue to close it if all is OK. Hang on...

**Comment by minduch** [comment]
Yes: it's fixed in the new build without the version 12.0.1 jars (and 12.0.2).
Sorry about the report, we should have checked better.
