### ISSUE TITLE
Jetty9.4.4 jdk1.8 ByteBuffer.limit() Nosuchmethoderror

### ISSUE THREAD

**Issue by kvopencode** [eclipse/jetty.project#4634]
Dear team, I am experiencing the below issue post upgrade of jetty9.4.4 in my dev. Please find below the details. Unfortunately my application cant be moved / upgraded to Java9/higher. Do we have a solution for this to run in jdk1.8 ? Do we have a jetty-util version which does the typecasting (Buffer). Any timely help is much appreciated.
<img width="759" alt="Screenshot 2020-03-04 at 09 19 11" src="https://user-images.githubusercontent.com/954768/75864010-49864e80-5df9-11ea-8258-8c6a02826849.png">

Jetty version - 9.4.4 v20180619
JDK version - 1.8.0_201
OS version - Red hat enterprise linux server release 6.10 (Santiago)
Attached the error log

**Comment by sbordet** [comment]
See https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495322586.

Please upgrade to a recent Jetty version such as 9.4.27.

**Comment by kvopencode** [comment]
> See [#3244 (comment)](https://github.com/eclipse/jetty.project/issues/3244#issuecomment-495322586).
> 
> Please upgrade to a recent Jetty version such as 9.4.27.

Yes i went through the comment sbordet. Can you please confirm if jetty 9.4.27 works fine with JDK1.8_201 ?

**Comment by joakime** [comment]
> Can you please confirm if jetty 9.4.27 works fine with JDK1.8_201 ?

Jetty 9.4.27 will work with Java 1.8.0 update 201 just fine.
See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.27.v20200227/pom.xml#L1920-L1931

However, JDK 1.8.0 update 201 is old and expired (in April 2019).
See: https://www.oracle.com/technetwork/java/javase/8u201-relnotes-5209271.html

Don't expect anything related to SSL/TLS to work properly (due to that JDK update being expired).
