### ISSUE TITLE
 org.eclipse.jetty.server.UserIdentity Not Found after Jetty Upgrade

### ISSUE THREAD

**Issue by ychaydhari** [eclipse/jetty.project#12722]
We are upgrading Jetty from 11.0.19 to 12.0.14, But after upgrading we are getting following error

java: cannot access org.eclipse.jetty.server.UserIdentity
  class file for org.eclipse.jetty.server.UserIdentity not found

Jetty versions we are using

jetty-server: 12.0.14
jetty-ee10-servlet - 12.0.14
jetty-util: 12.0.14

We are following below page from upgrade but not found any content related to UserIdentity class
https://jetty.org/docs/jetty/12/programming-guide/migration/11-to-12.html

Java version :- OpenJDk 17

**Comment by janbartel** [comment]
It's `org.eclipse.jetty.security.UserIdentity`.

**Comment by aparna-c-trellix** [comment]
I found a similar error when I upgraded from Jetty 9.x to 12.x , below is the error
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/server/UserIdentity$Scope
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)

Inspite of adding " implementation 'org.eclipse.jetty:jetty-security:12.0.16'", still this error occurs.

**Comment by joakime** [comment]
Nothing in Jetty 12 looks for that internal class `org/eclipse/jetty/server/UserIdentity$Scope`.
Either you are using that class directly in your own code, have a 3rd party dependency that somehow needs that internal class (which would be super strange as that internal class has no use outside of Jetty 9/10/11 internals), or you have a mix of Jetty versions in your classpath where an old version of a Jetty artifact is requesting it.
